export const UPDATE_VALUTE = "UPDATE_VALUTE";
export const ASYNC_API = "ASYNC_API";

export const CHANGE_VALUTE_DEFAULT_COUPLE_ONE_SELECT_ONE = "CHANGE_VALUTE_DEFAULT_COUPLE_ONE_SELECT_ONE";
export const CHANGE_VALUTE_DEFAULT_COUPLE_ONE_SELECT_TWO = "CHANGE_VALUTE_DEFAULT_COUPLE_ONE_SELECT_TWO";
export const CHANGE_VALUTE_DEFAULT_COUPLE_TWO_SELECT_ONE = "CHANGE_VALUTE_DEFAULT_COUPLE_TWO_SELECT_ONE";
export const CHANGE_VALUTE_DEFAULT_COUPLE_TWO_SELECT_TWO = "CHANGE_VALUTE_DEFAULT_COUPLE_TWO_SELECT_TWO";

export const CHANGE_DEFAULT_COUPLE_ONE_INPUTS = "CHANGE_DEFAULT_COUPLE_ONE_INPUTS";
export const CHANGE_DEFAULT_COUPLE_TWO_INPUTS = "CHANGE_DEFAULT_COUPLE_TWO_INPUTS";